<?php

namespace App\Enum;

enum NotificationType: string
{
    case MESSAGE = 'MESSAGE';
    case SIGNALEMENT = 'SIGNALEMENT';
    case SIGNALEMENT_URGENT = 'SIGNALEMENT_URGENT';
    case AVIS_PUBLIE = 'AVIS_PUBLIE';
    case AVIS_STATUT = 'AVIS_STATUT';
    case AVIS_REJETE = 'AVIS_REJETE';
    case AVIS_EN_ATTENTE = 'AVIS_EN_ATTENTE';
    case NOUVEL_AVIS_REGION = 'NOUVEL_AVIS_REGION';
    case AVIS_A_VALIDER = 'AVIS_A_VALIDER';
    case SUIVI_QUOTIDIEN = 'SUIVI_QUOTIDIEN';
    case DEMANDE_VALIDATION = 'DEMANDE_VALIDATION';
    case CONFIRMATION_RETROUVE = 'CONFIRMATION_RETROUVE';
    case MESSAGE_SIGNALE = 'MESSAGE_SIGNALE';
    case COMPTE_DESACTIVE = 'COMPTE_DESACTIVE';
    case COMPTE_REACTIVE = 'COMPTE_REACTIVE';
    case SYSTEM = 'SYSTEM';
}
